# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pow Wow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pow Wow
  pod 'Parse'
  pod 'AlamofireImage'
  pod 'SideMenu'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'Pow WowTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Pow WowUITests' do
    # Pods for testing
  end

end
